# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version = 1.0.0
maven_group = me.shiiyuko
archives_base_name = Manosaba-NeoForge-1.21.1

# Minecraft / NeoForge
minecraft_version = 1.21.1
neo_version = 21.1.115

# Mappings
mappings_channel = official
mappings_version = 1.21.1

# Kotlin & Compose
kotlin_version = 2.1.0
compose_version = 1.7.3

# Java
java_version = 21
